#!/usr/bin/env python3
"""Vendor the page's webfonts so it needs no network.

Fetches the Google Fonts stylesheet, keeps only the latin / latin-ext subsets,
downloads each woff2 next to it and rewrites the URLs to local paths. Google
serves one variable file per (family, subset) covering every weight, so several
@font-face blocks legitimately share a file -- the download is keyed on the URL,
the filename on the URL too, so they all point at something that exists.

    python tools/vendor_fonts.py      # rewrites static/css/fonts.css
"""

import os
import re
import urllib.request

CSS_URL = ("https://fonts.googleapis.com/css2"
           "?family=Google+Sans:wght@400;500;700"
           "&family=Noto+Sans:wght@400;600;700&display=swap")
# css2 hands back ttf to unknown clients and woff2 to modern browsers.
UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/120.0 Safari/537.36")
KEEP = {"latin", "latin-ext"}
FONT_DIR = "static/fonts"
OUT = "static/css/fonts.css"


def get(url):
    return urllib.request.urlopen(
        urllib.request.Request(url, headers={"User-Agent": UA}), timeout=30).read()


def main():
    css = get(CSS_URL).decode("utf-8")
    # The stylesheet is a run of "/* subset */ @font-face { ... }" blocks.
    blocks = re.findall(r"/\*\s*([a-z0-9-]+)\s*\*/\s*(@font-face\s*\{[^}]*\})", css)
    os.makedirs(FONT_DIR, exist_ok=True)

    names, out = {}, []
    for subset, block in blocks:
        if subset not in KEEP:
            continue
        fam = re.search(r"font-family:\s*'([^']+)'", block).group(1)
        weight = re.search(r"font-weight:\s*(\d+)", block).group(1)
        src = re.search(r"url\((https://fonts\.gstatic\.com/[^)]+)\)", block).group(1)

        # One name per URL, so shared variable files resolve for every weight.
        if src not in names:
            names[src] = "%s-%s.woff2" % (fam.lower().replace(" ", "-"), subset)
            open(os.path.join(FONT_DIR, names[src]), "wb").write(get(src))
        out.append("/* %s %s %s */\n%s"
                   % (fam, weight, subset, block.replace(src, "../fonts/" + names[src])))

    header = ("/* Google Sans + Noto Sans, subset to latin/latin-ext and vendored\n"
              "   locally so the page needs no network.\n"
              "   Generated by tools/vendor_fonts.py -- do not edit by hand. */\n\n")
    open(OUT, "w", encoding="utf-8").write(header + "\n\n".join(out) + "\n")
    print("%d faces over %d files -> %s" % (len(out), len(names), OUT))


if __name__ == "__main__":
    main()
